blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions & Help
    url: https://your-team.slack.com/channels/engineering
    about: Ask questions and get help from the team
  - name: 💬 Discussions
    url: https://github.com/your-org/your-repo/discussions
    about: General discussions about the project